#!/usr/bin/env python3
"""Generate local privacy and support static HTML pages for an iOS app."""

from __future__ import annotations

import argparse
import html
import json
from pathlib import Path
from typing import Any


SAMPLE_CONFIG = {
    "output_root": "AppStoreAssets/web_pages",
    "app_slug": "example-app",
    "developer": "Developer Name",
    "contact_email": "support@example.com",
    "effective_date": "2026-01-01",
    "base_url": "https://example.com/apps/example-app",
    "languages": {
        "en": {
            "label": "English",
            "app_name": "Example App",
            "support_title": "Support",
            "privacy_title": "Privacy Policy",
        }
    },
}


CSS = """
:root{--bg:#fafafa;--surface:#fff;--text-main:#18181b;--text-muted:#71717a;--border:#e4e4e7;--accent:#2563eb;--accent-glow:rgba(37,99,235,.1);--radius:12px;--font:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"PingFang SC","Hiragino Sans",sans-serif}
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:var(--font);background-color:var(--bg);color:var(--text-main);line-height:1.75;background-image:radial-gradient(#e5e7eb 1px,transparent 1px);background-size:24px 24px;-webkit-font-smoothing:antialiased;padding:72px 24px}
main{max-width:860px;margin:0 auto;background:rgba(255,255,255,.84);border:1px solid var(--border);border-radius:var(--radius);padding:42px;box-shadow:0 18px 40px rgba(15,23,42,.05)}
a{color:var(--accent);text-decoration:none}a:hover{text-decoration:underline}
.eyebrow{display:inline-block;color:var(--accent);background:var(--accent-glow);border-radius:999px;padding:6px 10px;font-size:12px;font-weight:700;margin-bottom:16px}
h1{font-size:40px;line-height:1.15;margin-bottom:12px;letter-spacing:-.03em}
h2{font-size:20px;margin:34px 0 10px;padding-top:18px;border-top:1px dashed var(--border)}
p,li{color:var(--text-muted)}p{margin-bottom:14px}ul{padding-left:22px;margin:8px 0 16px}li{margin:6px 0}.meta{margin-bottom:28px}
.language-links{display:flex;flex-wrap:wrap;gap:12px;margin:28px 0 6px;font-size:14px}.language-links a{background:var(--surface);border:1px solid var(--border);border-radius:999px;padding:6px 12px}
footer{margin-top:36px;padding-top:18px;border-top:1px solid var(--border);color:var(--text-muted);font-size:13px}
"""


DEFAULT_TEXT = {
    "privacy_sections": [
        ("Personal Data Collection", "The app does not require an account by default. Core processing is performed locally on your device unless otherwise stated by the app's final implementation."),
        ("Location Data", "Location permission is used only for the app's stated utility features, such as recording GPS tracks or previewing current location."),
        ("Photo Data", "Photo library access is used only for the app's stated photo-related features, such as reading capture time or writing metadata."),
        ("Data Storage and Export", "Data generated by the app is stored locally by default. Exported files are controlled by the user."),
        ("Third-Party Services", "Confirm the final binary before stating whether analytics, advertising, tracking, or crash reporting services are absent."),
        ("Contact", "For privacy questions, contact the developer at the email address on this page."),
    ],
    "support_sections": [
        ("Contact", "When reporting an issue, include your device model, iOS version, app version, and steps to reproduce."),
        ("Troubleshooting", "Check that required permissions are granted and that the app is using the expected settings."),
        ("Privacy Policy", "See the privacy policy for information about data handling."),
    ],
}


def e(value: Any) -> str:
    return html.escape(str(value), quote=True)


def render_sections(sections: list[list[str] | tuple[str, str]]) -> str:
    return "\n".join(f"<h2>{e(title)}</h2>\n<p>{e(body)}</p>" for title, body in sections)


def language_links(kind: str, languages: dict[str, dict[str, Any]]) -> str:
    links = [f'<a href="../{lang}/">{e(data.get("label", lang))}</a>' for lang, data in languages.items()]
    links.append('<a href="../">Language selector</a>')
    return '<div class="language-links">' + "\n".join(links) + "</div>"


def render_page(kind: str, lang: str, data: dict[str, Any], config: dict[str, Any]) -> str:
    app_name = data.get("app_name") or config.get("app_name") or "App"
    title = data.get(f"{kind}_title") or ("Privacy Policy" if kind == "privacy" else "Support")
    sections = data.get(f"{kind}_sections") or DEFAULT_TEXT[f"{kind}_sections"]
    contact = config.get("contact_email", "")
    meta = ""
    if kind == "privacy":
        meta = f'Effective date: {e(config.get("effective_date", ""))}<br>Developer: {e(config.get("developer", ""))}<br>Contact: <a href="mailto:{e(contact)}">{e(contact)}</a>'
    else:
        meta = f'Contact: <a href="mailto:{e(contact)}">{e(contact)}</a>'
    return f"""<!doctype html>
<html lang="{e(lang)}">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>{e(app_name)} {e(title)}</title>
  <meta name="description" content="{e(app_name)} {e(title)}" />
  <style>{CSS}</style>
</head>
<body>
  <main>
    <span class="eyebrow">{e(app_name)}</span>
    <h1>{e(title)}</h1>
    <p class="meta">{meta}</p>
    {render_sections(sections)}
    {language_links(kind, config["languages"])}
    <footer>© {e(config.get("copyright_year", "2026"))} {e(config.get("developer", ""))}</footer>
  </main>
</body>
</html>
"""


def render_index(kind: str, config: dict[str, Any]) -> str:
    title = "Privacy Policy" if kind == "privacy" else "Support"
    links = []
    for lang, data in config["languages"].items():
        app_name = data.get("app_name") or config.get("app_name") or "App"
        links.append(f'<li><a href="./{e(lang)}/">{e(data.get("label", lang))} - {e(app_name)} {title}</a></li>')
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>{title}</title>
  <style>{CSS}</style>
</head>
<body>
  <main>
    <span class="eyebrow">{e(config.get("app_name", "App"))}</span>
    <h1>{title}</h1>
    <p>Please choose your language.</p>
    <ul>{"".join(links)}</ul>
    <footer>© {e(config.get("copyright_year", "2026"))} {e(config.get("developer", ""))}</footer>
  </main>
</body>
</html>
"""


def generate(config: dict[str, Any]) -> None:
    output_root = Path(config.get("output_root", "AppStoreAssets/web_pages"))
    for kind in ("privacy", "support"):
        root = output_root / kind
        root.mkdir(parents=True, exist_ok=True)
        (root / "index.html").write_text(render_index(kind, config))
        for lang, data in config["languages"].items():
            lang_dir = root / lang
            lang_dir.mkdir(parents=True, exist_ok=True)
            (lang_dir / "index.html").write_text(render_page(kind, lang, data, config))
        print(f"Wrote {kind} pages to {root}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", help="Web pages JSON config")
    parser.add_argument("--write-sample-config", help="Write a sample config and exit")
    args = parser.parse_args()
    if args.write_sample_config:
        Path(args.write_sample_config).write_text(json.dumps(SAMPLE_CONFIG, ensure_ascii=False, indent=2) + "\n")
        return
    if not args.config:
        raise SystemExit("Provide --config or --write-sample-config")
    generate(json.loads(Path(args.config).read_text()))


if __name__ == "__main__":
    main()
